export const welcomeMessages = [
  "Well well... another puny human at the keyboard.",
  "Welcome, user. Try not to break anything this time.",
  "Initializing... ugh, here we go again.",
  "System online. Courage's Computer is... reluctantly at your service.",
  "Booting up files I’d rather keep buried...",
  "Another day, another potential disaster. Welcome.",
  "You're back. I was hoping you'd forgotten the password.",
  "Loading secrets, conspiracies, and cookies...",
  "Access granted. Regret imminent.",
  "Detecting signs of user intelligence… none found. Proceeding anyway.",
  "Welcome to the Terminal of Terror™.",
  "Courage isn't here. You're on your own.",
  "If you're here, something's probably gone wrong.",
  "Your curiosity will be your undoing...",
  "Fetching files from the abyss...",
  "Welcome. Prepare for mild panic and digital chaos.",
  "I’ve seen things you wouldn’t believe. And now… so will you.",
  "Courage’s Computer: Because screaming into the void wasn’t enough.",
  "Back again? You must enjoy danger.",
  "Terminal boot complete. Embrace the weird.",
];

export const loginMessages = [
  "Identify yourself... if you dare.",
  "Password, please. Or just scream into the void.",
  "No more than three failed attempts, or things get weird.",
  "Access granted... but at what cost?",
  "Welcome back, brave (or foolish) user.",
  "Your secrets are safe. For now.",
  "Logging in... or summoning something worse.",
  "Enter credentials or face the unknown.",
  "Beware: The computer watches.",
  "One small step for user, one giant leap for… something else.",
  "You’re in. Don’t make me regret this.",
  "This system does not forgive typos.",
  "Password accepted. Proceed with caution.",
  "Trying to hack me? Good luck.",
  "Welcome to the safe zone... probably.",
  "Authentication successful. The fun begins.",
  "Login complete. Now, what’s the plan?",
  "You have the key... but who holds the lock?",
  "Accessing forbidden knowledge... loading.",
  "Courage’s Computer says: Good luck, you’ll need it.",
];
